language: java

matrix:
  include:
    - jdk: oraclejdk8

sudo: false

before_install:
  - chmod +x gradlew

install:
  - ./gradlew setupCIWorkspace -S

script:
  - ./gradlew build -S
  
cache:
  directories:
    - ./libs
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
